import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import * as schema from "./schema";

export type Database = NodePgDatabase<typeof schema>;

export interface DbHandle {
  db: Database;
  pool: Pool;
}

export function createDb(connectionString: string): DbHandle {
  const pool = new Pool({ connectionString });
  return { db: drizzle(pool, { schema }), pool };
}

// Applies the plain .sql files in ./drizzle (generated by `npm run db:generate`).
export async function runMigrations(db: Database): Promise<void> {
  await migrate(db, { migrationsFolder: "./drizzle" });
}
